# Проект по эконометрике

In [112]:
import pandas as pd
import numpy as np

In [113]:
df = pd.read_csv('all_data_llm_tennis_moskow.csv')
df = df.rename(columns={'index':'rang_id'})
df

,has_secondary_sport_education,has_higher_sport_education,sport_master,sport_master_kandidate,is_champion,work_experience,master_id,category,details,master_id.1,...,contract,cur_score,profi_ru_start,photos_count,achivements,experience,education,additional_info,about_coach,coach5_cols
0,True,False,False,False,False,4.0,https://profi.ru/profile/BazylevPN/,NaN,NaN,https://profi.ru/profile/AbelkhairovaSV/,...,NaN,50.493489,29,10,NaN,На сервисе с декабря 2023 г. (2 года)\nФотогра...,"РУС ГЦОЛИФК, реабилитация, ЛФКс 2023 г. (3 года)",NaN,Если ты всегда мечтал научиться играть в больш...,; На сервисе с декабря 2023 г. (2 года)\nФотог...
1,True,False,False,False,False,19.0,https://profi.ru/profile/BazylevPN/,NaN,NaN,https://profi.ru/profile/AbramovMB/,...,NaN,50.433670,2,0,NaN,На сервисе с марта 2026 г,NaN,NaN,NaN,; На сервисе с марта 2026 г; ; ;
2,False,True,True,False,True,8.0,https://profi.ru/profile/BazylevPN/,NaN,NaN,https://profi.ru/profile/AbyasovaAN/,...,NaN,50.350443,31,0,NaN,На сервисе с октября 2023 г. (2 года),NaN,NaN,"Стаж: 6 лет\nМастер спорта, многократный побед...",; На сервисе с октября 2023 г. (2 года); ; ; С...
3,True,False,False,False,False,2.0,https://profi.ru/profile/BazylevPN/,NaN,NaN,https://profi.ru/profile/AfanasyevBA4/,...,NaN,50.330329,15,8,NaN,"Компания СУЭК-КУЗБАСС МФСЦ""ГОРНЯК""2023–2025 гг...",АНО ДПО НАДПО программа дополнительного профес...,"Обучаю с ""0"". За полгода работы,ученики участв...",Тренер по большому теннису. Провожу индивидуал...,"; Компания СУЭК-КУЗБАСС МФСЦ""ГОРНЯК""2023–2025 ..."
4,True,False,True,False,False,3.0,https://profi.ru/profile/BazylevPN/,NaN,NaN,https://profi.ru/profile/AgureyevaKM2/,...,NaN,50.512069,8,0,Мастер спорта по теннису2022 г.\nДокументы и с...,На сервисе с сентября 2025 г,NaN,NaN,Здравствуйте! Меня зовут Ксения! Я мастер спор...,Мастер спорта по теннису2022 г.\nДокументы и с...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
407,True,False,False,True,False,5.0,https://profi.ru/profile/BazylevPN/,NaN,NaN,https://profi.ru/profile/ZhirkovaVA10/,...,NaN,50.094330,2,2,NaN,На сервисе с марта 2026 г\nФотографии2,NaN,NaN,"Всем привет! Меня зовут Вероника, я тренер по ...",; На сервисе с марта 2026 г\nФотографии2; ; ; ...
408,True,False,False,False,False,13.0,https://profi.ru/profile/BazylevPN/,NaN,NaN,https://profi.ru/profile/ZhuchkovaVS3/,...,NaN,50.019230,9,0,NaN,На сервисе с августа 2025 г,NaN,NaN,Тренер по теннису & Спарринг-партнер | Все уро...,; На сервисе с августа 2025 г; ; ; Тренер по т...
409,True,False,True,False,True,9.0,https://profi.ru/profile/BazylevPN/,NaN,NaN,https://profi.ru/profile/ZhukovMA78/,...,NaN,50.461117,1,3,NaN,На сервисе с апреля 2026 г\nФотографии3,NaN,NaN,Профессиональный теннисист (ATP 449).\nМастер ...,; На сервисе с апреля 2026 г\nФотографии3; ; ;...
410,True,True,True,False,True,4.0,https://profi.ru/profile/BazylevPN/,NaN,NaN,https://profi.ru/profile/ZykovaDS2/,...,NaN,50.479362,33,2,Мастер спорта по теннису2022 г.\nФотографии2\n...,На сервисе с августа 2023 г. (2 года),NaN,NaN,"Здравствуйте, меня зовут Дарья!\nС 3х лет проф...",Мастер спорта по теннису2022 г.\nФотографии2\n...
411,True,False,True,False,False,18.0,https://profi.ru/profile/BazylevPN/,NaN,NaN,https://profi.ru/profile/user5599460/,...,NaN,50.438705,49,5,"Министерство спорта Российской Федерации, маст...",На сервисе с апреля 2022 г. (4 года),NaN,NaN,Мастер спорта РФ\nНа корте с 2005 года\nСтаж т...,"Министерство спорта Российской Федерации, маст..."

In [114]:
months = {'января': 1, 'февраля': 2, 'марта': 3, 'апреля': 4, 'мая': 5, 'июня': 6, 'июля': 7, 'августа': 8, 'сентября': 9, 'октября': 10, 'ноября': 11, 'декабря': 12}
def profiru_start_transformer(value):
    month_count = None
    if pd.notna(value):
        list_val = value.split()
        month = list_val[3]
        year = int(list_val[4])
        month_count = 12 * (2026 - year) + (5 - months[month])
    
    return month_count

df['is_highly_praised'] = df['is_highly_praised'].apply(lambda x: 1 if x==True else 0)
df['is_certified'] = df['is_certified'].apply(lambda x: 1 if x==True else 0)
df['docs_verified'] = df['docs_verified'].apply(lambda x: 1 if x==True else 0)
df['is_male'] = df['gender'].apply(lambda x: 1 if x=='MALE' else 0)
df.drop(columns=['gender'], inplace=True)

df.drop(columns=['contract'], inplace=True)
df.drop(columns=['insurance'], inplace=True)
df.drop(columns=['guarantee'], inplace=True)
df.drop(columns=['assembledInfoListing'], inplace=True)
df.drop(columns=['is_certified'], inplace=True)
df.drop(columns=['master_id'], inplace=True)
df.drop(columns=['category'], inplace=True)
df.drop(columns=['details'], inplace=True)
df.drop(columns=['discount'], inplace=True)

df.rename(columns={'profi_ru_start': 'months_on_profi_ru', 'price_socket': 'price', 'is_highly_praised': 'is_recomended', 'master_id.1': 'master_id'}, inplace=True)

df['cur_score'] = df['cur_score'].fillna(0)

df['rating'] = df['rating'].apply(lambda x: x.replace(',', '.')).astype('float')
df['has_price'] = df['price'].notna().astype('int')

df['has_secondary_sport_education'] = df['has_secondary_sport_education'].apply(lambda x: 1 if x=='True' else 0)
df['has_higher_sport_education'] = df['has_higher_sport_education'].apply(lambda x: 1 if x=='True' else 0)
df['sport_master'] = df['sport_master'].apply(lambda x: 1 if x=='True' else 0)
df['sport_master_kandidate'] = df['sport_master_kandidate'].apply(lambda x: 1 if x=='True' else 0)
df['is_champion'] = df['is_champion'].apply(lambda x: 1 if x=='True' else 0)


df['work_experience'] = df['work_experience'].fillna(df['months_on_profi_ru'] / 12)

df.loc[df['sport_master'] == 1, 'sport_master_kandidate'] = 0
df.loc[df['has_higher_sport_education'] == 1, 'has_secondary_sport_education'] = 0

df.drop(columns=['achivements', 'experience', 'education', 'additional_info', 'about_coach', 'coach5_cols'], inplace=True)

df

,has_secondary_sport_education,has_higher_sport_education,sport_master,sport_master_kandidate,is_champion,work_experience,master_id,rang_id,docs_verified,rating,reviews_count,is_recomended,price,cur_score,months_on_profi_ru,photos_count,is_male,has_price
0,1,0,0,0,0,4.0,https://profi.ru/profile/AbelkhairovaSV/,86.0,1,5.0,5,0,3200.0,50.493489,29,10,0,1
1,1,0,0,0,0,19.0,https://profi.ru/profile/AbramovMB/,111.0,0,0.0,0,0,NaN,50.433670,2,0,1,0
2,0,1,1,0,1,8.0,https://profi.ru/profile/AbyasovaAN/,100.0,0,0.0,0,0,NaN,50.350443,31,0,0,0
3,1,0,0,0,0,2.0,https://profi.ru/profile/AfanasyevBA4/,144.0,1,0.0,0,0,2000.0,50.330329,15,8,1,1
4,1,0,1,0,0,3.0,https://profi.ru/profile/AgureyevaKM2/,75.0,1,5.0,4,0,3000.0,50.512069,8,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
407,1,0,0,1,0,5.0,https://profi.ru/profile/ZhirkovaVA10/,136.0,0,0.0,0,0,3000.0,50.094330,2,2,0,1
408,1,0,0,0,0,13.0,https://profi.ru/profile/ZhuchkovaVS3/,136.0,0,0.0,0,0,NaN,50.019230,9,0,0,0
409,1,0,1,0,1,9.0,https://profi.ru/profile/ZhukovMA78/,103.0,1,0.0,0,0,NaN,50.461117,1,3,1,0
410,0,1,1,0,1,4.0,https://profi.ru/profile/ZykovaDS2/,84.0,0,5.0,1,0,5000.0,50.479362,33,2,0,1
411,1,0,1,0,0,18.0,https://profi.ru/profile/user5599460/,92.0,1,5.0,10,0,5000.0,50.438705,49,5,0,1

In [115]:
df.isna().sum()

has_secondary_sport_education     0
has_higher_sport_education        0
sport_master                      0
sport_master_kandidate            0
is_champion                       0
work_experience                   0
master_id                         0
rang_id                           0
docs_verified                     0
rating                            0
reviews_count                     0
is_recomended                     0
price                            93
cur_score                         0
months_on_profi_ru                0
photos_count                      0
is_male                           0
has_price                         0
dtype: int64

In [117]:
df.select_dtypes(exclude='object').mean()

has_secondary_sport_education       0.533981
has_higher_sport_education          0.422330
sport_master                        0.521845
sport_master_kandidate              0.089806
is_champion                         0.283981
work_experience                    10.618730
rang_id                            96.995146
docs_verified                       0.618932
rating                              3.274005
reviews_count                      10.060680
is_recomended                       0.097087
price                            3176.583072
cur_score                          50.334561
months_on_profi_ru                 49.905340
photos_count                        5.859223
is_male                             0.594660
has_price                           0.774272
dtype: float64

In [ ]:
# df.to_csv('processed_data_tennis.csv', index=False)

- 'has_secondary_education' - указал в профиле среднее спортивное образование и оно является высшей указанной в профиле ступенью образования
- 'has_higher_education' - указал в профиле высшее спортивное образование и оно является высшей указанной в профиле ступенью образования
- 'sport_master' - указал в профиле, что является мастером спорта и это является высшим указанным званием
- 'sport_master_kandidate' - указал в профиле, что является кандидатом в мастера спорта и это является высшим указанным званием
- 'is_champion' - является призером или победителем значимых соревнований на уровне мира или России
- 'work_experience' - число лет опыта
- 'master_id' - ссылка на профиль
-'rang_id' - место в выдаче
- 'docs_verified' - документы подтверждены Профи.ру
- 'rating' - рейтинг по отзывам (звездочки из 5 в профиле)
- 'reviews_count' - число отзывов
- 'is_recomended' - имеет в профиле плашку "Очень хвалят" от Профи.ру
- 'price' - цена 1 часа тренировки
- 'cur_score' - оценка по скоринговой модели с Профи.ру
- 'photos_count' - число фото с работой вне альбомов в профиле
- 'months_on_profi_ru' - сколько месяцев человек на Профи.ру
- 'is_male' - теренер мужчина
- 'has_price' - указана цена